
name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-20.04
    steps:
      - name: Metrics embed
        uses: gilesknap/metrics@latest
        with:
          token: ${{ github.token }}
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_traffic: yes

      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ github.token }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year