
name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-20.04
    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@1e8d436e6a48b0715730bba672583355026432cd
        with:
          token: ${{ secrets.METRICS }}
          config_timezone: Europe/London
          plugin_languages: yes
          plugin_traffic: yes
          plugin_followup: yes
          plugin_followup_sections: repositories, users
          plugin_followup_indepth: yes
          
